version: "3.8"
services:
  linux:
    container_name: linux
    volumes:
      - ./script:/stockholm
      - ./script/resources/infection:/home/infection
    working_dir: /stockholm
    environment:
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile